plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"
minecraft {
    mappings channel: mapping_channel, version: mapping_version
    copyIdeResources = true
    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        client {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        server {
            property 'forge.enabledGameTestNamespaces', mod_id
            args '--nogui'
        }
        gameTestServer {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        data {
            workingDirectory project.file('run-data')
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    mavenCentral()
    maven {
        url "https://cursemaven.com"
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    implementation 'net.dv8tion:JDA:5.3.2'
    jarJar('net.dv8tion:JDA:[5.3.2,6.0)') { dependency ->
        transitive = false
        jarJar.pin(dependency, '5.3.2')
    }

    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.9.24'
    jarJar('org.jetbrains.kotlin:kotlin-stdlib:[1.9,2.0)') { dependency ->
        transitive = false
        jarJar.pin(dependency, '1.9.24')
    }

    implementation 'com.neovisionaries:nv-websocket-client:2.14'
    jarJar('com.neovisionaries:nv-websocket-client:[2.14,3.0)') { dependency ->
        transitive = false
        jarJar.pin(dependency, '2.14')
    }

    implementation 'net.sf.trove4j:core:3.1.0'
    jarJar('net.sf.trove4j:core:[3.1,4.0)') { dependency ->
        transitive = false
        jarJar.pin(dependency, '3.1.0')
    }

    implementation 'club.minnced:discord-webhooks:0.8.4'
    jarJar('club.minnced:discord-webhooks:[0.8.4,1.0)') { dependency ->
        transitive = false
        jarJar.pin(dependency, '0.8.4')
    }

    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    jarJar('com.squareup.okhttp3:okhttp:[4.12,5.0)') { dependency ->
        transitive = false
        jarJar.pin(dependency, '4.12.0')
    }

    implementation 'com.squareup.okio:okio:3.9.0'
    jarJar('com.squareup.okio:okio:[3.9,4.0)') { dependency ->
        transitive = false
        jarJar.pin(dependency, '3.9.0')
    }

    implementation 'com.fasterxml.jackson.core:jackson-core:2.17.2'
    jarJar('com.fasterxml.jackson.core:jackson-core:[2.17,3.0)') { dependency ->
        transitive = false
        jarJar.pin(dependency, '2.17.2')
    }

    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.2'
    jarJar('com.fasterxml.jackson.core:jackson-databind:[2.17,3.0)') { dependency ->
        transitive = false
        jarJar.pin(dependency, '2.17.2')
    }

    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.17.2'
    jarJar('com.fasterxml.jackson.core:jackson-annotations:[2.17,3.0)') { dependency ->
        transitive = false
        jarJar.pin(dependency, '2.17.2')
    }

    implementation 'org.json:json:20240303'
    jarJar('org.json:json:[20240303,20250000)') { dependency ->
        transitive = false
        jarJar.pin(dependency, '20240303')
    }

    implementation 'org.apache.commons:commons-collections4:4.4'
    jarJar('org.apache.commons:commons-collections4:[4.4,5.0)') { dependency ->
        transitive = false
        jarJar.pin(dependency, '4.4')
    }

    implementation 'com.moandjiezana.toml:toml4j:0.7.2'
    jarJar('com.moandjiezana.toml:toml4j:[0.7,1.0)') { dependency ->
        transitive = false
        jarJar.pin(dependency, '0.7.2')
    }

    compileOnly("net.luckperms:api:5.4")
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version: minecraft_version, minecraft_version_range: minecraft_version_range,
            forge_version: forge_version, forge_version_range: forge_version_range,
            loader_version_range: loader_version_range,
            mod_id: mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
            mod_authors: mod_authors, mod_description: mod_description,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([

                'Specification-Title'     : mod_id,
                'Specification-Vendor'    : mod_authors,
                'Specification-Version'   : '1', // We are version 1 of ourselves
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.jar.archiveVersion,
                'Implementation-Vendor'   : mod_authors,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }

}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

jarJar.enable()

tasks.build.dependsOn(tasks.named("jarJar"))

tasks.jarJar.configure {
    archiveClassifier.set('all')
}
