modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="forgediscord"
version="${mod_version}"
displayName="ForgeDiscord"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.forgediscord]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.forgediscord]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.forgediscord]]
modId="luckperms"
mandatory=false
versionRange="[5.4,6)"
ordering="AFTER"
side="BOTH"
[[dependencies.forgediscord]]
modId="kotlinforforge"
mandatory=true
versionRange="[4.10,)"
ordering="AFTER"
side="BOTH"
[[dependencies.forgediscord]]
modId="obsidiancore"
mandatory=true
versionRange="[1.0.1]"
ordering="BEFORE"
side="BOTH"
